#!/usr/bin/env bash

if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
  printf 'init_a5_pd_validation.sh must be executed with bash, not sourced.\n' >&2
  return 2
fi

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACTION="${1:-help}"
CONFIG_DIR="${2:-}"
SITE_CONFIG="${3:-}"

POINTS=(
  pd_afd_graph_u2
  pd_afd_dspark_graph_u2
)
ROLES=(prefill decode proxy)

usage() {
  cat <<'EOF'
Usage:
  bash init_a5_pd_validation.sh list
  bash init_a5_pd_validation.sh init <config-dir> <absolute-site.env>

The init action creates two Graph/U2 integration points with prefill, decode, and proxy
role configs. It refuses to overwrite an existing config directory.
EOF
}

die() {
  printf '[a5-pd-config] ERROR: %s\n' "$*" >&2
  exit 2
}

list_points() {
  cat <<'EOF'
pd_afd_graph_u2              Flash checkpoint, PD + A4F4, Graph/U2
pd_afd_dspark_graph_u2       DSpark checkpoint, PD + A4F4, Graph/U2 + draft Graph
EOF
}

write_value() {
  local name="$1" value="$2"
  printf '%s=%q\n' "${name}" "${value}"
}

point_spec() {
  local point="$1"
  POINT_MODEL_PATH="${FLASH_MODEL_PATH}"
  POINT_EXECUTION_MODE=eager
  POINT_U_BATCHES=1
  POINT_ENABLE_DSPARK=0
  POINT_DSPARK_DRAFT_EXECUTION=eager
  case "${point}" in
    pd_afd_graph_u2)
      POINT_EXECUTION_MODE=full-decode-only
      POINT_U_BATCHES=2
      ;;
    pd_afd_dspark_graph_u2)
      POINT_MODEL_PATH="${DSPARK_MODEL_PATH}"
      POINT_EXECUTION_MODE=full-decode-only
      POINT_U_BATCHES=2
      POINT_ENABLE_DSPARK=1
      POINT_DSPARK_DRAFT_EXECUTION=graph
      ;;
    *) die "Unknown point: ${point}" ;;
  esac
}

write_role_config() {
  local point="$1" role="$2" output="$3"
  local run_root="${A5_PD_RUN_BASE}/${point}"
  {
    printf '# Generated by %s. Edit the site file, not this role file.\n' \
      "${SCRIPT_DIR}/init_a5_pd_validation.sh"
    printf 'source %q\n' "${SITE_CONFIG}"
    write_value AFD_PD_COMMIT "${RESOLVED_AFD_COMMIT}"
    write_value DEPLOYMENT_VARIANT pd_afd
    write_value MATRIX_POINT "${point}"
    write_value NODE_ROLE "${role}"
    write_value RUN_ROOT "${run_root}"
    write_value STATE_ROOT "${run_root}/state/${role}"
    write_value LOG_ROOT "${run_root}/logs/${role}"
    write_value VALIDATION_ROOT "${run_root}/validation"
    write_value OUTPUT_ROOT "${run_root}/output"
    write_value MODEL_PATH "${POINT_MODEL_PATH}"
    write_value PREFILL_DEVICES 0,1,2,3,4,5,6,7
    write_value ATTENTION_DEVICES 0,1,2,3
    write_value FFN_DEVICES 4,5,6,7
    write_value PREFILL_DP_SIZE 2
    write_value PREFILL_TP_SIZE 4
    write_value ATTENTION_RANKS 4
    write_value FFN_RANKS 4
    write_value DECODE_DP_SIZE 4
    write_value DECODE_TP_SIZE 1
    write_value AFD_PLACEMENT colocated
    write_value DECODE_EXECUTION_MODE "${POINT_EXECUTION_MODE}"
    write_value DECODE_U_BATCHES "${POINT_U_BATCHES}"
    write_value DECODE_ENABLE_MTP 0
    write_value DECODE_MTP_DRAFT_EXECUTION eager
    write_value DECODE_MTP_NUM_SPECULATIVE_TOKENS 1
    write_value DECODE_ENABLE_DSPARK "${POINT_ENABLE_DSPARK}"
    write_value DECODE_DSPARK_DRAFT_EXECUTION "${POINT_DSPARK_DRAFT_EXECUTION}"
    write_value DECODE_DSPARK_NUM_SPECULATIVE_TOKENS auto
    write_value AFD_ASYNC_SCHEDULING off
    write_value AFD_HCCL_GRAPH_U2_COMPUTE_OVERLAP 1
    write_value AFD_HCCL_GRAPH_U2_HYBRID_DAG 1
    write_value AFD_HCCL_GRAPH_U2_ATTENTION_THREE_STREAM 1
    write_value AFD_HCCL_GRAPH_U2_FFN_RECV_STREAM 1
    write_value AFD_HCCL_GRAPH_U2_FFN_CROSS_LAYER 1
  } >"${output}"
}

case "${ACTION}" in
  help|-h|--help)
    usage
    exit 0
    ;;
  list)
    list_points
    exit 0
    ;;
  init) ;;
  *)
    usage >&2
    die "Unknown action: ${ACTION}"
    ;;
esac

[[ -n "${CONFIG_DIR}" && -n "${SITE_CONFIG}" ]] \
  || die "init requires <config-dir> and <absolute-site.env>"
[[ "${SITE_CONFIG}" == /* ]] || die "site.env path must be absolute"
[[ -f "${SITE_CONFIG}" ]] || die "Missing site config: ${SITE_CONFIG}"
[[ ! -e "${CONFIG_DIR}" ]] || die "Config directory already exists: ${CONFIG_DIR}"

set -a
# shellcheck disable=SC1090
source "${SITE_CONFIG}"
set +a

for required_name in \
  AFD_PLUGIN_ROOT FLASH_MODEL_PATH DSPARK_MODEL_PATH PREFILL_IP DECODE_IP \
  NIC_NAME CANN_ROOT A5_PD_RUN_BASE; do
  value="${!required_name:-}"
  [[ -n "${value}" ]] || die "${required_name} is empty in ${SITE_CONFIG}"
  [[ "${value}" != *CHANGE_ME* ]] \
    || die "Replace ${required_name}=${value} in ${SITE_CONFIG}"
done

git -C "${AFD_PLUGIN_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1 \
  || die "Not a git checkout: ${AFD_PLUGIN_ROOT}"
RESOLVED_AFD_COMMIT="${AFD_PD_COMMIT:-auto}"
if [[ "${RESOLVED_AFD_COMMIT}" == "auto" ]]; then
  RESOLVED_AFD_COMMIT="$(git -C "${AFD_PLUGIN_ROOT}" rev-parse HEAD)"
fi
[[ "${RESOLVED_AFD_COMMIT}" =~ ^[0-9a-f]{40}$ ]] \
  || die "AFD_PD_COMMIT must resolve to a 40-character commit"

SITE_CONFIG="$(readlink -f "${SITE_CONFIG}")"
mkdir -p "${CONFIG_DIR}"
for point in "${POINTS[@]}"; do
  point_spec "${point}"
  for role in "${ROLES[@]}"; do
    write_role_config "${point}" "${role}" \
      "${CONFIG_DIR}/${point}-${role}.env"
  done
done

printf '[a5-pd-config] generated %s role configs in %s\n' \
  "$(( ${#POINTS[@]} * ${#ROLES[@]} ))" "${CONFIG_DIR}"
printf '[a5-pd-config] afd-plugin commit: %s\n' "${RESOLVED_AFD_COMMIT}"
